name: konaf_skora
description: "A new Flutter project."

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  bloc: ^8.1.4
  cached_network_image: ^3.4.1
  cupertino_icons: ^1.0.8
  dartz: ^0.10.1
  device_preview: ^1.2.0
  dio: ^5.7.0
  file_picker: ^8.1.4
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_localization: ^0.2.1
  flutter_rating_bar: ^4.0.1
  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.0.16
  fluttertoast: ^8.2.8
  freezed_annotation: ^2.4.4
  geocoding: ^3.0.0
  geolocator: ^13.0.2
  get_it: ^8.0.0
  go_router: ^14.2.8
  image_picker: ^1.1.2
  intl: ^0.19.0
  json_annotation: ^4.9.0
  lottie: ^3.1.3
  mime: ^2.0.0
  path: ^1.9.0
  pin_code_fields: ^8.0.1
  shared_preferences: ^2.2.3
  shimmer: ^3.0.0
  skeletonizer: ^1.4.2

dev_dependencies:
  build_runner: ^2.4.13
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.5.7
  json_serializable: ^6.7.0

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/fonts/
    - assets/svg/

  fonts:
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo-Regular.ttf
        - asset: assets/fonts/Cairo-Bold.ttf
          weight: 700
        - asset: assets/fonts/Cairo-Light.ttf
          weight: 300
